[package]
authors = ["Paul Mason <paul@form1.co.nz>"]
build = "build.rs"
categories = ["science", "mathematics", "data-structures", "no-std", "no-std::no-alloc"]
description = "Decimal number implementation written in pure Rust suitable for financial and fixed-precision calculations."
documentation = "https://docs.rs/rust_decimal/"
edition = "2024"
exclude = ["tests/generated/*"]
keywords = ["decimal", "financial", "fixed", "precision", "number"]
license = "MIT"
name = "rust_decimal"
readme = "./README.md"
repository = "https://github.com/paupino/rust-decimal"
rust-version = "1.85.0"
version = "2.0.0-alpha.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
arbitrary = { default-features = false, optional = true, version = "1" }
arrayvec = { default-features = false, version = "0.7" }
borsh = { default-features = false, features = ["derive", "unstable__schema"], optional = true, version = "1" }
bytemuck = { default-features = false, optional = true, version = "1.17.1" }
bytemuck_derive = { default-features = false, optional = true, version = "1.7.1" }
bytes = { default-features = false, optional = true, version = "1" }
diesel = { default-features = false, optional = true, version = "2" }
ndarray-0_16 = { default-features = false, optional = true, package = "ndarray", version = "0.16" }
num-traits = { default-features = false, features = ["i128"], package = "num-traits", version = "0.2" }
postgres-types = { default-features = false, optional = true, package = "postgres-types", version = "0.2" }
proptest = { default-features = false, optional = true, features = ["std"], version = "1.0" }
rand-0_9 = { default-features = false, optional = true, package = "rand", version = "0.9" }
rand-0_10 = { default-features = false, optional = true, package = "rand", version = "0.10" }
rocket = { default-features = false, optional = true, version = "0.5" }
rust_decimal_macros = { path = "macros", default-features = false, optional = true, version = "=2.0.0-alpha.0" }
serde = { default-features = false, optional = true, version = "1" }
serde_json = { default-features = false, optional = true, version = "1" }
zmij = { default-features = false, optional = true, version = "1" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { default-features = false, version = "0.2", optional = true }

[dev-dependencies]
criterion = { default-features = false, version = "0.5" }
csv = "1"
rust_decimal_macros = { path = "macros" }
serde = { default-features = false, features = ["derive"], version = "1.0" }
serde_json = "1.0"
version-sync = { default-features = false, features = ["html_root_url_updated", "markdown_deps_updated"], version = "0.9" }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen = { default-features = false, version = "0.2" }
wasm-bindgen-test = { version = "0.3" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
bincode = { default-features = false, version = "1.0" }
bytes = { default-features = false, version = "1.0" }
diesel = { default-features = false, features = ["mysql", "postgres"], version = "2.2.3" }
futures = { default-features = false, version = "0.3" }
postgres = { default-features = false, version = "0.19" }
rust_decimal = { path = ".", features = ["rand-0_9", "macros", "rocket-0_5-traits"] }
rand-0_9 = { default-features = false, features = ["thread_rng"], package = "rand", version = "0.9" }
rand-0_10 = { default-features = false, features = ["thread_rng"], package = "rand", version = "0.10" }
rkyv-0_8 = { version = "0.8", package = "rkyv" }
tokio = { default-features = false, features = ["macros", "rt-multi-thread", "test-util"], version = "1.0" }
tokio-postgres = { default-features = false, version = "0.7" }

[features]
default = ["alloc", "serde", "std"]

align16 = [] # Force Decimal to be repr(align16) - the same as u128
alloc = []
borsh = ["dep:borsh", "std"]
bytemuck = ["c-repr", "dep:bytemuck", "dep:bytemuck_derive"]
c-repr = [] # Force Decimal to be repr(C)
db-diesel-mysql = ["diesel/mysql_backend", "std"]
db-diesel-postgres = ["diesel/postgres_backend", "std"]
db-diesel2-mysql = ["db-diesel-mysql"]
db-diesel2-postgres = ["db-diesel-postgres"]
db-postgres = ["dep:bytes", "dep:postgres-types", "std"]
db-tokio-postgres = ["dep:bytes", "dep:postgres-types", "std"]
macros = ["dep:rust_decimal_macros"]
maths = ["alloc"]
maths-nopanic = ["maths"]
ndarray-0_16 = ["dep:ndarray-0_16"]
proptest = ["dep:proptest"]
rand-0_9 = ["dep:rand-0_9"]
rand-0_10 = ["dep:rand-0_10"]
rocket-0_5-traits = ["dep:rocket", "std"]
rust-fuzz = ["dep:arbitrary"]
serde = ["alloc", "dep:serde", "wasm-bindgen?/serde"]
serde-arbitrary-precision = ["serde-with-arbitrary-precision"]
serde-bincode = ["serde-str"] # Backwards compatability
serde-float = ["serde-with-float"]
serde-str = ["serde-with-str"]
serde-with-arbitrary-precision = ["serde", "serde_json/arbitrary_precision", "serde_json/std", "zmij"]
serde-with-float = ["serde"]
serde-with-str = ["serde"]
std = ["alloc", "arrayvec/std", "borsh?/std", "bytes?/std", "rand-0_9?/std", "rand-0_10?/std", "serde?/std", "serde_json?/std", "wasm-bindgen?/std"]
tokio-pg = ["db-tokio-postgres"] # Backwards compatability
wasm = ["dep:wasm-bindgen"]

[[bench]]
harness = false
name = "comparison"
path = "benches/comparison.rs"

[[test]]
name = "borsh_tests"
path = "tests/borsh_tests.rs"
required-features = ["borsh"]

[[test]]
name = "generated"
path = "tests/generated.rs"
test = false

[[test]]
name = "ndarray_tests"
path = "tests/ndarray_tests.rs"
required-features = ["ndarray-0_16"]

[[test]]
name = "postgres_tests"
path = "tests/postgres_tests.rs"
required-features = ["db-postgres"]

[[test]]
name = "proptest_tests"
path = "tests/proptest_tests.rs"
required-features = ["proptest"]

[[test]]
name = "rocket_tests"
path = "tests/rocket_tests.rs"
required-features = ["rocket-0_5-traits"]

[[test]]
name = "rust_fuzz_tests"
path = "tests/rust_fuzz_tests.rs"
required-features = ["rust-fuzz"]

[[test]]
name = "serde_tests"
path = "tests/serde_tests.rs"
required-features = ["serde"]

[[example]]
name = "rkyv-remote"
required-features = ["macros"]

[workspace]
members = [
    ".",
    "./macros",
]
resolver = "2"
