[target.'cfg(all())']
rustflags = [
    # BEGIN - Embark standard lints v0.4
    # do not change or add/remove here, but one can add exceptions after this section
    # for more info see: <https://github.com/EmbarkStudios/rust-ecosystem/issues/59>
    "-Aclippy::inconsistent_digit_grouping",
    "-Aclippy::large_digit_groups",
    "-Aclippy::excessive_precision",
    "-Aclippy::zero_prefixed_literal",
]

